// Banque de questions - MA GUINÉE
// Chaque question : { q: "...", choices: [...], answer: index, explain: "..." }
// Catégories : histoire-geo, institutions, culture, citoyennete

const QUESTIONS = {
  "histoire-geo": {
    label: "Histoire & Géographie",
    icon: "🗺️",
    color: "#009460",
    items: [
      { q: "Quelle est la capitale de la Guinée ?", choices: ["Kankan", "Conakry", "Labé", "N'Zérékoré"], answer: 1, explain: "Conakry est aussi le plus grand port et le principal centre économique du pays." },
      { q: "En quelle année la Guinée a-t-elle obtenu son indépendance ?", choices: ["1956", "1958", "1960", "1962"], answer: 1, explain: "La Guinée a proclamé son indépendance le 2 octobre 1958." },
      { q: "Qui fut le premier président de la République de Guinée ?", choices: ["Lansana Conté", "Alpha Condé", "Ahmed Sékou Touré", "Sékou Camara"], answer: 2, explain: "Il dirigera la Guinée sans interruption de 1958 jusqu'à sa mort en 1984." },
      { q: "De quelle puissance coloniale la Guinée a-t-elle obtenu son indépendance ?", choices: ["Royaume-Uni", "Portugal", "Belgique", "France"], answer: 3, explain: "La Guinée fut la seule colonie française d'Afrique à voter 'Non' au référendum de 1958, choisissant l'indépendance immédiate." },
      { q: "Quel grand fleuve d'Afrique de l'Ouest prend sa source en Guinée ?", choices: ["Le Nil", "Le fleuve Niger", "Le Congo", "Le Zambèze"], answer: 1, explain: "Sa source se trouve dans le massif du Fouta Djallon, avant qu'il ne traverse le Mali, le Niger et le Nigeria." },
      { q: "La région du Fouta Djallon est surnommée :", choices: ["Le grenier de l'Afrique", "Le château d'eau de l'Afrique de l'Ouest", "La porte du Sahara", "Le poumon vert"], answer: 1, explain: "Plusieurs grands fleuves ouest-africains, dont le Niger, le Sénégal et la Gambie, y prennent leur source." },
      { q: "Quelles sont les 4 régions naturelles de la Guinée ?", choices: ["Nord, Sud, Est, Ouest", "Basse Guinée, Moyenne Guinée, Haute Guinée, Guinée forestière", "Côtière, Montagneuse, Désertique, Insulaire", "Maritime, Sahélienne, Tropicale, Équatoriale"], answer: 1, explain: "Chacune a ses propres paysages, son climat et ses ethnies dominantes." },
      { q: "Lequel de ces pays NE partage PAS de frontière avec la Guinée ?", choices: ["Sénégal", "Mali", "Côte d'Ivoire", "Ghana"], answer: 3, explain: "La Guinée partage ses frontières avec six pays : Guinée-Bissau, Sénégal, Mali, Côte d'Ivoire, Liberia et Sierra Leone." },
      { q: "Quel océan borde la Guinée ?", choices: ["Océan Indien", "Océan Pacifique", "Océan Atlantique", "Mer Méditerranée"], answer: 2, explain: "Sa façade maritime s'étend sur environ 300 km." },
      { q: "Conakry, la capitale, est principalement construite sur :", choices: ["Une montagne", "La presqu'île de Tombo", "Une île volcanique", "Un plateau désertique"], answer: 1, explain: "La ville s'est ensuite étendue sur le continent le long de la presqu'île de Kaloum." },
      { q: "La Haute Guinée était historiquement liée à quel grand empire médiéval ouest-africain ?", choices: ["L'Empire du Mali", "L'Empire Ottoman", "L'Empire Romain", "L'Empire Khmer"], answer: 0, explain: "Cette région est aujourd'hui encore majoritairement peuplée par les Malinkés, héritiers de cet empire." },
      { q: "Qui est Samori Touré ?", choices: ["Un explorateur français", "Un chef d'État actuel", "Un résistant qui a combattu la colonisation française", "Un footballeur guinéen"], answer: 2, explain: "Il fonda l'empire Wassoulou et résista pendant près de 16 ans à la conquête française." },
      { q: "Quelle est la devise nationale de la Guinée ?", choices: ["Unité, Progrès, Justice", "Travail, Justice, Solidarité", "Liberté, Égalité, Fraternité", "Paix, Travail, Patrie"], answer: 1, explain: "Cette devise figure sur les armoiries officielles du pays." },
      { q: "Quel est le nom de l'hymne national de la Guinée ?", choices: ["Liberté", "Guinée Debout", "La Guinéenne", "Hymne du Peuple"], answer: 0, explain: "Il fut adopté dès l'indépendance en 1958." },
      { q: "Dans quel ordre apparaissent les couleurs du drapeau guinéen (de la hampe vers l'extérieur) ?", choices: ["Vert, Jaune, Rouge", "Rouge, Jaune, Vert", "Jaune, Rouge, Vert", "Rouge, Vert, Jaune"], answer: 1, explain: "Ce sont aussi les couleurs panafricaines, reprises par plusieurs autres pays du continent." },
      { q: "Que symbolise généralement la couleur verte du drapeau guinéen ?", choices: ["Le sang des martyrs", "La végétation et l'espoir", "L'océan", "Le ciel"], answer: 1, explain: "Le rouge symbolise le sang versé pour l'indépendance, et le jaune le soleil et les richesses du sous-sol." },
      { q: "Quelle grande région montagneuse traverse la Moyenne Guinée ?", choices: ["Le Fouta Djallon", "Les Monts Atlas", "Le massif du Kilimandjaro", "Le Drakensberg"], answer: 0, explain: "Ce massif couvre une grande partie de la Moyenne Guinée et abrite un climat plus frais que le reste du pays." },
      { q: "Quel sommet est souvent cité parmi les points les plus élevés de la Guinée, partagé avec la Côte d'Ivoire ?", choices: ["Le Mont Kilimandjaro", "Le Mont Nimba", "Le Mont Cameroun", "Le Mont Kenya"], answer: 1, explain: "Il culmine à 1 752 mètres d'altitude." },
      { q: "La Guinée est parfois appelée 'Guinée Conakry' pour la distinguer de :", choices: ["La Guinée équatoriale et la Guinée-Bissau", "L'Angola", "Le Nigeria", "Le Gabon"], answer: 0, explain: "Trois pays africains différents portent le nom de 'Guinée' dans le monde." },
      { q: "Le 2 octobre est célébré en Guinée comme :", choices: ["La fête du travail", "Le jour de l'indépendance", "La fête des récoltes", "Le nouvel an"], answer: 1, explain: "C'est un jour férié, marqué par des défilés dans tout le pays." },
      { q: "Quelle est la superficie approximative de la Guinée ?", choices: ["145 857 km²", "245 857 km²", "345 857 km²", "445 857 km²"], answer: 1, explain: "C'est un peu plus petit que le Royaume-Uni." },
      { q: "Comment s'appelle l'aéroport international de Conakry ?", choices: ["Aéroport Ahmed Sékou Touré", "Aéroport Houphouët-Boigny", "Aéroport Léopold Sédar Senghor", "Aéroport Kotoka"], answer: 0, explain: "Il est situé à Gbessia, dans la commune de Matoto." },
      { q: "Quelle ville est traditionnellement surnommée la deuxième ville de Guinée ?", choices: ["Kankan", "Boké", "Mamou", "Faranah"], answer: 0, explain: "Kankan est aussi un grand centre commercial et religieux de la Haute Guinée." },
      { q: "Siguiri, dans le nord-est de la Guinée, est réputée pour :", choices: ["L'orpaillage (extraction d'or)", "La pêche en eau douce uniquement", "L'industrie textile", "Le tourisme de montagne"], answer: 0, explain: "La région produit une part importante de l'or extrait en Guinée, de manière artisanale et industrielle." },
      { q: "Le Mont Nimba, point culminant partagé avec la Côte d'Ivoire, est classé par l'UNESCO comme :", choices: ["Patrimoine mondial (réserve naturelle)", "Simple parc d'attraction", "Zone industrielle", "Aéroport international"], answer: 0, explain: "La réserve abrite une biodiversité exceptionnelle, dont des chimpanzés connus pour utiliser des outils." },
      { q: "De 1958 à 1984, les armoiries de la Guinée comportaient quel animal, symbole de puissance et de sagesse ?", choices: ["Un éléphant", "Un lion", "Un aigle", "Un hippopotame"], answer: 0, explain: "Ce n'est plus le cas depuis la réforme des armoiries de 1997, centrées sur une colombe." },
      { q: "Vers 1235, quelle bataille a vu le prince mandingue Soundiata Keita vaincre le roi sosso Soumaoro Kanté, ouvrant la voie à l'Empire du Mali ?", choices: ["La bataille de Kirina", "La bataille d'Adwa", "La bataille de Tondibi", "La bataille de Koumbi Saleh"], answer: 0, explain: "Cette victoire fonde la légende de Soundiata Keita, héros de l'épopée mandingue encore racontée par les griots aujourd'hui." },
      { q: "La théocratie peule du Fouta Djallon, fondée en 1726, avait pour capitale :", choices: ["Timbo", "Labé", "Mamou", "Dalaba"], answer: 0, explain: "Timbo partageait le pouvoir avec Fugumba, siège religieux du conseil des sages." },
      { q: "Qui a fondé la théocratie du Fouta Djallon en lançant un jihad en 1726 ?", choices: ["Karamoko Alfa", "Samori Touré", "Sékou Touré", "El Hadj Omar Tall"], answer: 0, explain: "Il sera plus tard remplacé par son cousin Ibrahima Sori." },
      { q: "Quel explorateur français fut le premier Européen à atteindre Tombouctou (1828) et à en revenir vivant, après avoir traversé le Fouta Djallon ?", choices: ["René Caillié", "David Livingstone", "Henry Morton Stanley", "Pierre Savorgnan de Brazza"], answer: 0, explain: "Il voyagea déguisé en musulman égyptien pour traverser des régions alors fermées aux Européens." },
      { q: "Lors du référendum de 1958 sur la Communauté française proposée par De Gaulle, la Guinée a voté :", choices: ["Non, choisissant l'indépendance immédiate", "Oui, restant dans la Communauté", "Elle n'a pas participé au vote", "Le vote a été annulé"], answer: 0, explain: "Sékou Touré aurait déclaré préférer 'la liberté dans la pauvreté à l'opulence dans l'esclavage'." },
      { q: "De 1958 à 1984, la Guinée a été dirigée comme un État à parti unique autour du :", choices: ["PDG (Parti Démocratique de Guinée)", "RPG", "UFDG", "RDA uniquement"], answer: 0, explain: "Toute opposition politique organisée était alors interdite." },
      { q: "Ahmed Sékou Touré est décédé en mars 1984 :", choices: ["Lors d'une opération cardiaque aux États-Unis", "Lors d'un accident d'avion", "Assassiné à Conakry", "De vieillesse à Timbo"], answer: 0, explain: "Sa mort ouvrira la voie au coup d'État de Lansana Conté quelques jours plus tard." },
      { q: "Le coup d'État qui a porté Lansana Conté au pouvoir a eu lieu le 3 avril 1984, soit :", choices: ["Une semaine après la mort de Sékou Touré", "Le jour de l'indépendance", "Dix ans après l'indépendance", "Juste avant l'indépendance"], answer: 0, explain: "Le nouveau pouvoir libérera aussi les prisonniers politiques détenus à Camp Boiro." },
      { q: "Lansana Conté a dirigé la Guinée pendant environ combien d'années, jusqu'à sa mort en décembre 2008 ?", choices: ["24 ans", "5 ans", "10 ans", "40 ans"], answer: 0, explain: "Son règne a vu la transition progressive vers le multipartisme dans les années 1990." },
      { q: "Après la mort de Lansana Conté en décembre 2008, qui a pris le pouvoir par un coup d'État militaire ?", choices: ["Moussa Dadis Camara", "Sékouba Konaté", "Alpha Condé", "Mamadi Doumbouya"], answer: 0, explain: "Il dirigera la junte CNDD (Conseil national pour la démocratie et le développement)." },
      { q: "Le 28 septembre 2009, au stade de Conakry, les forces de sécurité ont réprimé dans le sang :", choices: ["Un rassemblement pacifique de l'opposition", "Un match de football", "Un concert", "Une cérémonie religieuse"], answer: 0, explain: "Cet évènement a fait l'objet d'enquêtes internationales et d'un procès historique qui s'est conclu en 2024." },
      { q: "En 2010, la Guinée a connu un évènement politique inédit depuis son indépendance :", choices: ["Sa première alternance démocratique, avec l'élection d'Alpha Condé", "Son premier coup d'État", "Son adhésion à l'ONU", "La création de sa monnaie"], answer: 0, explain: "C'était la première fois qu'un président accédait au pouvoir par une élection disputée plutôt que par un coup d'État ou une succession automatique." },
      { q: "En mars 2020, un référendum constitutionnel controversé a permis à Alpha Condé de :", choices: ["Se présenter à un troisième mandat", "Démissionner immédiatement", "Dissoudre l'Assemblée Nationale", "Changer la capitale"], answer: 0, explain: "Ce scrutin provoqua d'importantes manifestations et une répression dénoncée par plusieurs organisations de défense des droits humains." },
      { q: "Alpha Condé a dirigé la Guinée entre 2010 et 2021, soit environ :", choices: ["11 ans", "3 ans", "30 ans", "50 ans"], answer: 0, explain: "Il sera renversé par un coup d'État militaire le 5 septembre 2021, dirigé par Mamadi Doumbouya." }
    ]
  },
  "institutions": {
    label: "Institutions & Gouvernement",
    icon: "🏛️",
    color: "#CE1126",
    items: [
      { q: "Quel organe est traditionnellement chargé de voter les lois en Guinée ?", choices: ["L'Assemblée Nationale", "La Cour Suprême", "Le Conseil des ministres", "La mairie de Conakry"], answer: 0 },
      { q: "Où siège l'Assemblée Nationale de Guinée ?", choices: ["Kankan", "Labé", "Conakry", "Boké"], answer: 2 },
      { q: "Un État démocratique classique repose sur combien de pouvoirs (branches) ?", choices: ["2", "3", "4", "5"], answer: 1, explain: "Exécutif, législatif et judiciaire." },
      { q: "Qui exerce principalement le pouvoir exécutif dans un État comme la Guinée ?", choices: ["Le Président et le gouvernement", "Les députés", "Les juges", "Les maires"], answer: 0 },
      { q: "Quel document fondamental définit l'organisation de l'État et les droits des citoyens ?", choices: ["Le code civil", "La Constitution", "Le journal officiel", "Le code pénal"], answer: 1 },
      { q: "Quel est le rôle principal d'un député à l'Assemblée Nationale ?", choices: ["Gérer une entreprise privée", "Voter les lois et contrôler l'action du gouvernement", "Diriger l'armée", "Nommer les juges"], answer: 1 },
      { q: "Quel est le nom de la monnaie guinéenne ?", choices: ["Le CFA", "Le Franc guinéen", "Le Dollar", "Le Cedi"], answer: 1 },
      { q: "Sous l'autorité du président, qui dirige en général le gouvernement au quotidien ?", choices: ["Le Premier ministre", "Le maire de Conakry", "Le gouverneur de région", "Le chef de village"], answer: 0 },
      { q: "Quel pouvoir est chargé de rendre la justice et d'appliquer les lois ?", choices: ["Le pouvoir exécutif", "Le pouvoir législatif", "Le pouvoir judiciaire", "Le pouvoir religieux"], answer: 2 },
      { q: "Une élection présidentielle permet avant tout aux citoyens de :", choices: ["Choisir leur chef d'État", "Payer moins d'impôts", "Changer de nationalité", "Élire un maire"], answer: 0 },
      { q: "À partir de quel âge un citoyen guinéen peut-il généralement voter ?", choices: ["16 ans", "18 ans", "21 ans", "25 ans"], answer: 1 },
      { q: "Quelle institution est généralement chargée de veiller au respect de la Constitution ?", choices: ["La Cour Constitutionnelle", "La police municipale", "Le ministère du Commerce", "La chambre de commerce"], answer: 0 },
      { q: "Comment appelle-t-on l'ensemble des lois fondamentales qui organisent un pays ?", choices: ["Le règlement intérieur", "La Constitution", "Le protocole", "Le décret"], answer: 1 },
      { q: "Quelle ville est le siège du gouvernement guinéen ?", choices: ["Kindia", "Mamou", "Conakry", "Faranah"], answer: 2 },
      { q: "Quand une loi est votée par l'Assemblée Nationale puis signée par le Président, on dit qu'elle est :", choices: ["Annulée", "Promulguée", "Suspendue", "Abrogée"], answer: 1 },
      { q: "Qui représente généralement un État à l'étranger dans les relations diplomatiques ?", choices: ["Les enseignants", "Le Président de la République et les ambassadeurs", "Les commerçants", "Les journalistes"], answer: 1 },
      { q: "Comment appelle-t-on le scrutin où les citoyens choisissent leurs représentants ?", choices: ["Un recensement", "Une élection", "Un sondage", "Une pétition"], answer: 1 },
      { q: "Qu'est-ce qu'un ministère ?", choices: ["Un parti politique", "Une organisation gouvernementale chargée d'un domaine précis (santé, éducation...)", "Un tribunal", "Une banque privée"], answer: 1 },
      { q: "Qu'est-ce que la séparation des pouvoirs ?", choices: ["Diviser un pays en régions", "Répartir les pouvoirs entre institutions distinctes pour éviter les abus", "Séparer les partis politiques", "Diviser l'armée"], answer: 1 },
      { q: "Qu'est-ce qu'un gouverneur de région en Guinée ?", choices: ["Un chef religieux", "Un représentant de l'État au niveau régional", "Un chef d'entreprise", "Un enseignant"], answer: 1 },
      { q: "Qui a présidé le Conseil National de la Transition (CNT), organe législatif créé après 2021 en remplacement de l'ancienne Assemblée Nationale ?", choices: ["Dansa Kourouma", "Bah Oury", "Alpha Condé", "Lansana Conté"], answer: 0 },
      { q: "En juillet 2026, la Guinée a installé son premier Parlement élu, combien d'années après le coup d'État de 2021 ?", choices: ["5 ans", "1 an", "10 ans", "20 ans"], answer: 0 },
      { q: "Pour la première fois depuis l'indépendance, l'Assemblée Nationale guinéenne doit disposer d'un siège construit spécialement pour elle, situé à :", choices: ["Koloma (commune de Ratoma)", "Kaloum", "Kankan", "Kindia"], answer: 0, explain: "En attendant la fin des travaux, le Parlement siège au Palais du Peuple, à Kaloum, comme depuis l'indépendance." }
    ]
  },
  "culture": {
    label: "Culture & Société",
    icon: "🎭",
    color: "#FCD116",
    items: [
      { q: "Quelle est la langue officielle de l'administration guinéenne ?", choices: ["L'anglais", "Le français", "L'arabe", "Le portugais"], answer: 1 },
      { q: "Laquelle de ces langues est une langue nationale parlée en Guinée ?", choices: ["Le Soussou", "Le Swahili", "Le Zoulou", "L'Amharique"], answer: 0 },
      { q: "Quel groupe est traditionnellement majoritaire en Moyenne Guinée (Fouta Djallon) ?", choices: ["Les Soussous", "Les Peuls (Foulah)", "Les Kissi", "Les Toma"], answer: 1 },
      { q: "Quel groupe est traditionnellement majoritaire en Haute Guinée ?", choices: ["Les Malinkés (Maninka)", "Les Baga", "Les Guerzé", "Les Landouma"], answer: 0 },
      { q: "Quel groupe est traditionnellement majoritaire en Basse Guinée ?", choices: ["Les Malinkés", "Les Toma", "Les Soussous", "Les Peuls"], answer: 2 },
      { q: "La Guinée forestière regroupe notamment quelles ethnies ?", choices: ["Kissi, Toma, Guerzé", "Peuls, Malinkés", "Soussous, Baga", "Wolofs, Sérères"], answer: 0 },
      { q: "La Kora, instrument à cordes associé à la culture mandingue, est une sorte de :", choices: ["Tambour", "Harpe-luth", "Flûte", "Trompette"], answer: 1 },
      { q: "Quel ensemble artistique guinéen a popularisé les danses traditionnelles guinéennes dans le monde ?", choices: ["Les Ballets Africains", "L'Orchestre National", "Le Cirque Guinéen", "Le Théâtre de Conakry"], answer: 0 },
      { q: "Qu'est-ce que le fonio ?", choices: ["Un instrument de musique", "Une céréale traditionnelle ouest-africaine", "Un tissu traditionnel", "Une danse"], answer: 1 },
      { q: "Quelle est la religion majoritaire en Guinée ?", choices: ["Le christianisme", "L'islam", "L'animisme", "Le bouddhisme"], answer: 1 },
      { q: "Mory Kanté, célèbre artiste guinéen connu mondialement, jouait principalement de quel instrument ?", choices: ["La guitare électrique", "Le piano", "La kora", "Le violon"], answer: 2 },
      { q: "Quel sport est le plus populaire en Guinée ?", choices: ["Le basketball", "Le football", "Le tennis", "Le rugby"], answer: 1 },
      { q: "Comment est surnommée l'équipe nationale masculine de football de Guinée ?", choices: ["Les Lions", "Le Syli national", "Les Aigles", "Les Panthères"], answer: 1 },
      { q: "Le mot 'Syli' signifie en langue locale :", choices: ["Lion", "Éléphant", "Aigle", "Soleil"], answer: 1 },
      { q: "Quelle tenue traditionnelle est souvent portée lors des grandes occasions en Guinée ?", choices: ["Le kimono", "Le boubou", "Le sari", "Le poncho"], answer: 1 },
      { q: "Le balafon, instrument emblématique de la musique mandingue, est fabriqué notamment avec :", choices: ["Des calebasses et des lamelles de bois", "Du métal uniquement", "Du verre", "Du plastique"], answer: 0 },
      { q: "Dans la tradition orale ouest-africaine, qui est chargé de transmettre l'histoire des familles et des royaumes ?", choices: ["Le forgeron", "Le griot", "Le chasseur", "Le pêcheur"], answer: 1 },
      { q: "Quelle fête religieuse musulmane est largement célébrée en Guinée après le mois de jeûne ?", choices: ["L'Aïd el-Fitr", "Le Nouvel An chinois", "Hanouka", "Diwali"], answer: 0 },
      { q: "La Tabaski (Aïd el-Kebir) commémore notamment :", choices: ["La fête des récoltes", "Le sacrifice d'Abraham", "L'indépendance", "Le nouvel an"], answer: 1 },
      { q: "Le riz est un aliment de base très présent dans la cuisine guinéenne, souvent préparé en :", choices: ["Riz gras / riz sauce", "Sushi", "Paella", "Risotto"], answer: 0 },
      { q: "Quel oiseau figure au sommet des armoiries actuelles de la République de Guinée, tenant une branche d'olivier dans son bec ?", choices: ["Une colombe", "Un aigle", "Un perroquet", "Une hirondelle"], answer: 0, explain: "Les armoiries actuelles datent de 1997 ; la base de l'écu porte les couleurs rouge, or et vert." },
      { q: "Comment appelle-t-on les habitants de la Guinée ?", choices: ["Les Guinéens", "Les Ghanéens", "Les Gambiens", "Les Gabonais"], answer: 0 },
      { q: "Où se trouve le Musée National de Guinée ?", choices: ["À Conakry", "À Kankan", "À Labé", "À Kindia"], answer: 0 },
      { q: "Bembeya Jazz National, orchestre guinéen emblématique, est connu pour :", choices: ["Sa musique moderne inspirée des traditions mandingues", "Le football", "La politique étrangère", "L'agriculture"], answer: 0 },
      { q: "Les Amazones de Guinée sont connues comme :", choices: ["Un orchestre entièrement féminin", "Une équipe de football féminin", "Une association de commerçantes", "Un groupe de danse masculin"], answer: 0 },
      { q: "Sekouba Bambino Diabaté est un artiste guinéen célèbre pour :", choices: ["Le chant", "La sculpture", "La politique", "L'architecture"], answer: 0 }
    ]
  },
  "citoyennete": {
    label: "Actualité & Citoyenneté",
    icon: "🤝",
    color: "#1b1b1b",
    items: [
      { q: "Qu'est-ce que la citoyenneté ?", choices: ["Un sport", "L'appartenance à un État, avec des droits et des devoirs", "Un diplôme scolaire", "Une religion"], answer: 1 },
      { q: "Lequel de ces éléments est un devoir du citoyen ?", choices: ["Respecter la loi", "Ignorer les règles", "Éviter de voter", "Refuser de payer ses impôts"], answer: 0 },
      { q: "Lequel de ces éléments est un droit fondamental du citoyen ?", choices: ["Le droit à l'éducation", "Le droit de ne pas respecter la loi", "Le droit de frauder", "Le droit de polluer"], answer: 0 },
      { q: "Qu'est-ce qu'un référendum ?", choices: ["Un match de football", "Un vote direct des citoyens sur une question précise", "Un recensement de population", "Un impôt"], answer: 1 },
      { q: "Pourquoi est-il important de voter aux élections ?", choices: ["Pour gagner de l'argent", "Pour participer aux décisions qui concernent le pays", "Pour éviter l'école", "Parce que c'est obligatoire partout dans le monde"], answer: 1 },
      { q: "Quel est le rôle principal de l'école dans la société ?", choices: ["Occuper le temps libre", "Éduquer et former les citoyens de demain", "Remplacer la famille", "Organiser des élections"], answer: 1 },
      { q: "Qu'est-ce que la solidarité nationale ?", choices: ["La compétition entre régions", "L'entraide entre les citoyens d'un même pays", "Le commerce international", "La séparation des communautés"], answer: 1 },
      { q: "Quel est l'objectif principal du développement durable ?", choices: ["Épuiser les ressources rapidement", "Répondre aux besoins actuels sans compromettre l'avenir", "Augmenter la pollution", "Arrêter toute production"], answer: 1 },
      { q: "La Guinée est l'un des premiers réservoirs mondiaux de quel minerai, utilisé pour produire l'aluminium ?", choices: ["L'or", "Le diamant", "La bauxite", "Le cuivre"], answer: 2 },
      { q: "Qu'est-ce que le civisme ?", choices: ["Le respect des règles de la vie en société", "Un sport collectif", "Une fête nationale", "Un type de musique"], answer: 0 },
      { q: "Pourquoi faut-il respecter le bien public (routes, écoles, hôpitaux) ?", choices: ["Parce qu'ils appartiennent à toute la communauté", "Parce qu'ils appartiennent à l'État seul", "Parce que personne n'en a besoin", "Parce qu'ils sont inutiles"], answer: 0 },
      { q: "Que signifie le sigle ONG ?", choices: ["Organisation Nationale du Gouvernement", "Organisation Non Gouvernementale", "Organisme National de Gestion", "Office National des Garanties"], answer: 1 },
      { q: "La Guinée est membre de quelle organisation régionale ouest-africaine favorisant l'intégration économique ?", choices: ["L'Union Européenne", "La CEDEAO", "L'ASEAN", "Le Mercosur"], answer: 1 },
      { q: "La Guinée est membre de quelle grande organisation panafricaine ?", choices: ["L'Union Africaine", "L'OTAN", "L'OPEP uniquement", "Le G7"], answer: 0 },
      { q: "La Guinée est membre de quelle organisation internationale regroupant presque tous les pays du monde ?", choices: ["L'ONU", "La NASA", "L'OMS uniquement", "Interpol uniquement"], answer: 0 },
      { q: "Pourquoi l'éducation des filles est-elle importante pour le développement d'un pays ?", choices: ["Elle n'a pas d'impact", "Elle contribue à réduire les inégalités et à développer la société", "Elle concerne seulement les garçons", "Elle remplace l'école publique"], answer: 1 },
      { q: "Qu'est-ce que la corruption ?", choices: ["Un abus de pouvoir ou de confiance pour un avantage personnel illégitime", "Une fête traditionnelle", "Un type d'impôt légal", "Une forme de solidarité"], answer: 0 },
      { q: "Pourquoi est-il important de dénoncer les actes de corruption ?", choices: ["Pour préserver la justice et l'équité dans la société", "Pour créer des conflits", "Parce que c'est sans conséquence", "Pour ralentir l'économie"], answer: 0 },
      { q: "Protéger l'environnement est important pour la Guinée afin de :", choices: ["Préserver les ressources naturelles pour les générations futures", "Augmenter la déforestation", "Réduire l'agriculture", "Ignorer le climat"], answer: 0 },
      { q: "Qu'est-ce qu'un citoyen responsable peut faire pour sa communauté ?", choices: ["S'impliquer, respecter autrui et contribuer au bien commun", "Ignorer les lois", "Éviter tout engagement", "Refuser de participer à la vie collective"], answer: 0 }
    ]
  },
  "actuel": {
    label: "Guinée Aujourd'hui",
    icon: "📰",
    color: "#C9641D",
    items: [
      { q: "Le coup d'État qui a porté Mamadi Doumbouya au pouvoir a eu lieu le :", choices: ["5 septembre 2021", "2 octobre 1958", "28 décembre 2025", "15 mai 2010"], answer: 0 },
      { q: "Mamadi Doumbouya a été élu président de la République lors de l'élection présidentielle du :", choices: ["28 décembre 2025", "2 octobre 1958", "15 mars 2021", "5 septembre 2021"], answer: 0, explain: "Soit quatre ans après le coup d'État de 2021." },
      { q: "Avec quel score Mamadi Doumbouya a-t-il été élu président en 2025 ?", choices: ["86,72 % des voix", "51 % des voix", "60 % des voix", "99 % des voix"], answer: 0 },
      { q: "En septembre 2026, pourquoi France 24 a-t-elle présenté des excuses officielles au président Mamadi Doumbouya ?", choices: ["Un journaliste l'avait qualifié de « président putschiste »", "Elle avait annulé un match de football", "Elle avait mal traduit l'hymne national", "Elle avait publié une fausse carte du pays"], answer: 0, explain: "La chaîne avait été suspendue par la Haute Autorité de la Communication avant de présenter ses excuses." },
      { q: "En août 2026, combien de nouvelles préfectures le président Doumbouya a-t-il créées en une seule réforme ?", choices: ["11", "3", "25", "2"], answer: 0 },
      { q: "Après la réforme administrative d'août 2026, combien de préfectures compte désormais la Guinée ?", choices: ["44", "33", "50", "20"], answer: 0 },
      { q: "Quelles sont les deux nouvelles régions administratives créées en 2026 ?", choices: ["Beyla et Siguiri", "Kankan et Labé", "Kindia et Mamou", "Boké et Faranah"], answer: 0 },
      { q: "La ville de Kamsar, déjà connue pour l'exportation de bauxite, est devenue en 2026 :", choices: ["Une nouvelle préfecture", "La capitale du pays", "Une région autonome", "Un port franc international"], answer: 0 },
      { q: "Simandou, dans le sud-est de la Guinée, est l'un des plus grands gisements mondiaux de :", choices: ["Fer", "Pétrole", "Charbon", "Uranium"], answer: 0 },
      { q: "Le projet Simandou doit stimuler l'économie guinéenne grâce notamment à la construction :", choices: ["D'une voie ferrée et d'un port en eau profonde", "D'un aéroport spatial", "D'un canal maritime transcontinental", "D'un tunnel sous-marin vers le Sénégal"], answer: 0 },
      { q: "Les barrages de Kaléta et de Souapiti, construits sur le fleuve Konkouré, servent principalement à :", choices: ["Produire de l'électricité (hydroélectricité)", "Irriguer le désert", "Produire du sel", "Stocker du pétrole"], answer: 0 }
    ]
  }
};
